# Generated by Django 2.2.4 on 2019-08-30 12:39

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('image_analysis', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=image.models.get_upload_path)),
                ('transaction_status', models.SmallIntegerField(choices=[(0, 'Complete'), (1, 'In Progress'), (2, 'Failed')], default=1)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service External - Create Image base64',
            },
        ),
    ]
